export const FETCHING_ARTICLES = 'FETCHING_ARTICLES';
export const FETCHING_ERROR = 'FETCHING_ERROR';
export const GET_ARTICLES = 'GET_ARTICLES';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
